<a href="https://colab.research.google.com/github/chanduchow99/Machine-Learning/blob/main/ML_Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Create a random vector of size 15 with integers in the range 1-20
random_vector = np.random.randint(1, 21, size=15)

# Reshape the array to 3 by 5 and Print array shape
reshaped_array = random_vector.reshape(3, 5)
print("Array shape after reshaping:", reshaped_array.shape)

# Replace the max in each row by 0
max_indices = np.argmax(reshaped_array, axis=1)
for i, max_index in enumerate(max_indices):
    reshaped_array[i, max_index] = 0

print("Array after replacing max in each row with 0:\n", reshaped_array)


Array shape after reshaping: (3, 5)
Array after replacing max in each row with 0:
 [[ 0  2  9 13  2]
 [ 4 11  0 10 15]
 [10 11  0 19  7]]


In [ ]:
import numpy as np

# Creating a 2-dimensional array of size 4x3 with 4-byte integer elements
array = np.zeros((4, 3), dtype=np.int32)

# Printing shape, size, and data type of the array
print("Shape of the array:", array.shape)
print("Size of the array:", array.size)
print("Data type of the array:", array.dtype)

Shape of the array: (4, 3)
Size of the array: 12
Data type of the array: int32


In [ ]:
# Given array
e = np.array([[3, -2], [1, 0]])

# Computing eigenvalues and right eigenvectors
eigenvalues, right_eigenvectors = np.linalg.eig(e)

print("Eigenvalues:", eigenvalues)
print("Right Eigenvectors:\n", right_eigenvectors)

Eigenvalues: [2. 1.]
Right Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [ ]:
# Given array
array = np.array([[0, 1, 2], [3, 4, 5]])

# Computing the sum of diagonal elements
diagonal_sum = np.trace(array)

print("Sum of diagonal elements:", diagonal_sum)

Sum of diagonal elements: 4


In [ ]:
# Given array
array = np.array([[1, 2], [3, 4], [5, 6]])

# Reshape 3x2
reshaped_array_3x2 = np.reshape(array, (3, 2))

# Reshape 2x3
reshaped_array_2x3 = np.reshape(array, (2, 3))

print("Reshaped 3x2 array:\n", reshaped_array_3x2)
print("Reshaped 2x3 array:\n", reshaped_array_2x3)


Reshaped 3x2 array:
 [[1 2]
 [3 4]
 [5 6]]
Reshaped 2x3 array:
 [[1 2 3]
 [4 5 6]]
